6-Rename-RuRootRule-as-RuRulesManager
jecisc/Rules pull request #8
Opened 2019-11-14 16:54 UTC by juliendelplanque

Renamed RuRootRule  as RuRulesManager.
Renamed test class accordingly.
Fixed occurences in comments.

2019-11-18 10:33 UTC, jecisc commented
Documentation should also be updated.

2019-11-19 09:36 UTC, juliendelplanque commented
Done @jecisc

2019-11-19 09:49 UTC, jecisc requested changes

2019-11-19 09:49 UTC, jecisc commented on README.md
>  A root rule is a composite rule that will know the model which the rules should apply and that contains all the rules. It can be considered as the rules manager.
```suggestion
A rule manager is a composite rule that will know the model which the rules should apply and that contains all the rules.
```

2019-11-19 09:49 UTC, jecisc commented on documentation/Documentation.md
>  A root rule is a composite rule that will know the model which the rules should apply and that contains all the rules. It can be considered as the rules manager.
```suggestion
A rule manager is a composite rule that will know the model which the rules should apply and that contains all the rules.
```

2019-11-19 09:50 UTC, juliendelplanque commented
I just did a stupid find and replace :D. Sorry for the ones I missed.

2019-12-06 12:49 UTC, jecisc approved these changes

2019-12-06 12:49 UTC, merged